/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ddd87ed3-5b62-4d73-91a6-c5694bc4070b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wTQPgMnkc",
    "aws_user_pools_web_client_id": "fipclbnvg3pcqf9l8c8pl5558",
    "oauth": {}
};


export default awsmobile;
