/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ddd87ed3-5b62-4d73-91a6-c5694bc4070b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wTQPgMnkc",
    "aws_user_pools_web_client_id": "fipclbnvg3pcqf9l8c8pl5558",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jbi32dwbrvcibnowcn7tzl6eiu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rtctl6xel5calch2al7torxgom",
    "aws_user_files_s3_bucket": "amplifyapp6425457b16a64b8ebb228ffa3bda61c0124702-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
